no change     /shared/centos7/anaconda3/3.7/condabin/conda
no change     /shared/centos7/anaconda3/3.7/bin/conda
no change     /shared/centos7/anaconda3/3.7/bin/conda-env
no change     /shared/centos7/anaconda3/3.7/bin/activate
no change     /shared/centos7/anaconda3/3.7/bin/deactivate
no change     /shared/centos7/anaconda3/3.7/etc/profile.d/conda.sh
no change     /shared/centos7/anaconda3/3.7/etc/fish/conf.d/conda.fish
no change     /shared/centos7/anaconda3/3.7/shell/condabin/Conda.psm1
no change     /shared/centos7/anaconda3/3.7/shell/condabin/conda-hook.ps1
no change     /shared/centos7/anaconda3/3.7/lib/python3.7/site-packages/xontrib/conda.xsh
no change     /shared/centos7/anaconda3/3.7/etc/profile.d/conda.csh
no change     /home/agarwal.rishi/.bashrc
No action taken.
Traceback (most recent call last):
  File "Routine_Square_Code.py", line 10, in <module>
    ls5 = ee.ImageCollection('LANDSAT/LT05/C02/T1_L2')
  File "/home/agarwal.rishi/.conda/envs/ee/lib/python3.7/site-packages/ee/computedobject.py", line 32, in __call__
    return type.__call__(cls, *args, **kwargs)
  File "/home/agarwal.rishi/.conda/envs/ee/lib/python3.7/site-packages/ee/imagecollection.py", line 38, in __init__
    self.initialize()
  File "/home/agarwal.rishi/.conda/envs/ee/lib/python3.7/site-packages/ee/imagecollection.py", line 72, in initialize
    super(ImageCollection, cls).initialize()
  File "/home/agarwal.rishi/.conda/envs/ee/lib/python3.7/site-packages/ee/collection.py", line 32, in initialize
    apifunction.ApiFunction.importApi(cls, 'Collection', 'Collection')
  File "/home/agarwal.rishi/.conda/envs/ee/lib/python3.7/site-packages/ee/apifunction.py", line 183, in importApi
    cls.initialize()
  File "/home/agarwal.rishi/.conda/envs/ee/lib/python3.7/site-packages/ee/apifunction.py", line 154, in initialize
    signatures = data.getAlgorithms()
  File "/home/agarwal.rishi/.conda/envs/ee/lib/python3.7/site-packages/ee/data.py", line 1050, in getAlgorithms
    call = _get_cloud_api_resource().projects().algorithms().list(
  File "/home/agarwal.rishi/.conda/envs/ee/lib/python3.7/site-packages/ee/data.py", line 285, in _get_cloud_api_resource
    'Earth Engine client library not initialized. Run `ee.Initialize()`')
ee.ee_exception.EEException: Earth Engine client library not initialized. Run `ee.Initialize()`
/var/spool/slurm/d/job23845243/slurm_script: line 13: [27.436407359332986,-7.57841301205225],: command not found
/var/spool/slurm/d/job23845243/slurm_script: line 14: [27.436407359332986,-7.518171474050515],: command not found
/var/spool/slurm/d/job23845243/slurm_script: line 15: [27.350233348102517,-7.518171474050515]]: command not found
